enable-magisk-update = true
# patches-version = "v3.0.0-dev.4"


[YT]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Hide Shorts dimming' 'Hide shortcuts' 'MaterialYou' 'Change Version Code'"
excluded-patches = "'Disable splash animation' 'Enable debug logging'"
patcher-args = "-OiconType='Cairo' -OappIcon='mmt' -OappName='YouTube' -OdoubleTapLengthArrays='3, 5, 10, 15, 20, 30, 60, 120, 180' -OBackgroundColor='@android:color/transparent' -OpackageNameYouTube='rvx.android.youtube' -OiconType='rounded' -OchangeTopButtons=true -OchangeVersionCode=true -OsettingsLabel='eXtended' -OinsertPosition='@string/about_key' -OcornerRadius='4.0dip' -OdarkThemeBackgroundColor='?ytBaseBackground' -OlightThemeBackgroundColor='?ytBaseBackground' -OstrokeColor='?attr/ytChipBackground' -OdarkThemeBackgroundColor='@android:color/black' -OlightThemeBackgroundColor='@android:color/white' -OselectedTranslations='ar, id-rID, ja-rJP' -OsettingsMenuIcon='yt_alt'"